version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
            - npm i amazon-reviews-crawler

      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli