version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

      # install tiktok scrapper globally
      - npm i tiktok-scraper

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
